name: my_evacuate
description: A disaster alert and evacuation app
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^10.1.0
  http: ^1.1.0
  google_maps_flutter: ^2.5.0

flutter:
  uses-material-design: true
