name: wildfire
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  google_maps_flutter: ^2.12.1
  url_launcher: ^6.0.10
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  permission_handler: ^11.4.0
  geolocator: ^13.0.4
  geocoding: ^3.0.0
  cloud_firestore: ^5.6.6
  location: ^8.0.0
  xml: ^6.2.7
  google_generative_ai: ^0.2.1
  

  # Uncomment if needed
  # flutter_map: ^3.1.0
  # http: ^0.13.5
  # latlong2: ^0.8.1
  # positioned_tap_detector_2: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

dependency_overrides:
# positioned_tap_detector_2: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/layer.kml
    - assets/route.kml
    - assets/fire_starting.png
    - assets/evacuation.png
    - assets/smoke_inhalation.png
    - assets/burns.png
    - assets/first_aid.png
