name: wildfire
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.1.1
  url_launcher: ^6.0.10
  cupertino_icons: ^1.0.8
  # Uncomment the following dependencies if needed
  # flutter_map: ^3.1.0
  # http: ^0.13.5
  # latlong2: ^0.8.1
  # positioned_tap_detector_2: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

dependency_overrides:
# Uncomment this if you need a specific version
# positioned_tap_detector_2: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fire_starting.png
    - assets/evacuation.png
    - assets/smoke_inhalation.png
    - assets/burns.png
    - assets/first_aid.png
